apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      # Read entire configmap into environment variables
      envFrom:
        - configMapKeyRef:
            name: example-configmap
      # Read individual values from configmap into environment variables
      # env:
      #   - name: COLOR
      #     valueFrom:
      #       configMapKeyRef:
      #         name: example-configmap
      #         key: color
      volumeMounts:
      - mountPath: /var/i-am-empty
        name: emptydir-volume
      - mountPath: /var/config
        name: hostpath-volume
      - mountPath: /etc/conf
        name: config-volume
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh"] # Corrosponds to ENTRYPOINT
      args: ["-c", "while true; do sleep 30; done;"] # Corrosponds to CMD
      volumeMounts:
      - mountPath: /var/i-am-empty
        name: emptydir-volume
    # Example Ambassador container
    - name: mysql-proxy-ambassador
      image: mysql-proxy:latest
      ports:
        - containerPort: 3306 # Containers in pod can access at localhost:3306
      env:
      - name: DB_HOST
        value: mysql.xxx.us-east-1.rds.amazonaws.com
  volumes:
  - name: emptydir-volume
    emptyDir: {} # Initialize an emptyDir
  - name: hostpath-volume
    hostPath:
      path: /tmp # Path of the directory on the host node
  - name: config-volume
    configMap:
      name: example-configmap
