apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: prod
    tier: frontend
  annotations:
    tier: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
