apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  # clusterIP: none # Uncomment this to make the service headless
  type: ClusterIP
  ports:
    - port: 80 # Port exposed by the service
      protocol: TCP
      targetPort: 80 # Port to use for the pod(s)
  selector:
    run: nginx-clusterip