apiVersion: v1
kind: Pod
metadata:
  name: whoami1
  labels:
    app: whoami
spec:
  containers:
  - image: containous/whoami
    name: whoami1
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: whoami2
  labels:
    app: whoami
spec:
  containers:
  - image: containous/whoami
    name: whoami2
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-whoami
spec:
  type: NodePort
  selector: # Uses this Pod label to detect target pods
    app: whoami
  ports:
    - port: 80 # Port for the NodePort service itself
    # - nodeport: 30001 # (Valid values range from 30000 to 32767)
      targetPort: 80 # Port to access the Pod at