apiVersion: v1
kind: Service
metadata:
  name: nodeport-whoami
spec:
  type: NodePort
  selector: # Uses this Pod label to detect target pods
    app: whoami
  ports:
    - nodeport: 30001 # (Valid values range from 30000 to 32767)
      port: 80 # Port for the NodePort service itself
      targetPort: 80 # Port to access the Pod at