apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-pvc
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: persistentvolume-example
  volumes:
    - name: persistentvolume-example
      persistentVolumeClaim:
        claimName: pv-hostpath