apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: standard
  hostPath:
    path: /tmp/persistent-volume
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi