apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: standard
  hostPath:
    path: /tmp/persistent-volume
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-nfs
# spec:
#   storageClassName: standard
#   nfs:
#     path: /opt/nfs
#     server: nfs-server-host
#     fsType: ext4
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi